version: "3.7"

#
# [ services ]
#
services:
  server:
    image: add-connect:server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=14
    container_name: add-connect-server
    env_file: .env
    ports:
      - 45500:3000
    networks:
      - add-connect

  database:
    image: mongo
    container_name: add-connect-database
    networks:
      - add-connect
    ports:
      - 45501:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: add-connect

  redis:
    image: redis:alpine
    container_name: add-connect-cache
    restart: always
    ports:
      - 45503:6379
    networks:
      - add-connect

#
# [ networks ]
#
networks:
  add-connect:
    driver: bridge
    internal: true
